application: deck-writer
version: 1-0-0
runtime: go
api_version: go1
skip_files:
  - ^(.*/)?.*/node_modules/.*
  - ^(.*/)?.*/test/.*

handlers:

# part

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/image/(.*\.(gif|png|jpg))

- url: /(favicon.ico)
  static_files: static/image/\1
  upload: static/image/favicon.ico

- url: /style/(.*\.(css|map))
  static_files: static/style/\1
  upload: static/style/(.*\.(css|map))

- url: /script/(.*\.(js|map))
  static_files: static/script/\1
  upload: static/script/(.*\.(js|map))

- url: /font/(.*\.(eot|svg|ttf|woff))
  static_files: static/font/\1
  upload: static/font/(.*\.(eot|svg|ttf|woff))

- url: /api/.*
  script: _go_app